/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;
import java.time.LocalDate;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author micha
 */
public class BuatSuratJalanForm extends javax.swing.JPanel {

    private MainPage mainPage;
    /**
     * Creates new form BuatSuratJalan
     */
    public BuatSuratJalanForm(MainPage mainPage) {
        initComponents();
        addMainPage(mainPage);
    }
    
    public void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoiceNumberText = new javax.swing.JTextField();
        InvoiceNumberLabel = new javax.swing.JLabel();
        CustomerNameText = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerEmailText = new javax.swing.JTextField();
        CustomerEmailLabel = new javax.swing.JLabel();
        OrderDateText = new javax.swing.JTextField();
        OrderDateLabel = new javax.swing.JLabel();
        ItemsText = new javax.swing.JTextField();
        ItemsLabel = new javax.swing.JLabel();
        CreateSuratJalanButton = new javax.swing.JButton();
        DeliveryDateLabel = new javax.swing.JLabel();
        DeliveryDateText = new javax.swing.JTextField();

        InvoiceNumberLabel.setText("Invoice Number");

        CustomerNameLabel.setText("Customer Name");

        CustomerEmailLabel.setText("Customer Email");

        OrderDateLabel.setText("Order Date");

        ItemsLabel.setText("Items");

        CreateSuratJalanButton.setText("Create");
        CreateSuratJalanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateSuratJalanButtonActionPerformed(evt);
            }
        });

        DeliveryDateLabel.setText("Delivery Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateSuratJalanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderDateLabel)
                            .addComponent(CustomerEmailLabel)
                            .addComponent(ItemsLabel)
                            .addComponent(CustomerNameLabel)
                            .addComponent(InvoiceNumberLabel)
                            .addComponent(DeliveryDateLabel))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeliveryDateText)
                            .addComponent(InvoiceNumberText)
                            .addComponent(CustomerNameText)
                            .addComponent(CustomerEmailText)
                            .addComponent(OrderDateText)
                            .addComponent(ItemsText, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvoiceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvoiceNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeliveryDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateSuratJalanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateSuratJalanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateSuratJalanButtonActionPerformed
        // TODO add your handling code here:
        int dialogResult = mainPage.tampilkanConfirmDialog();
        if(dialogResult != JOptionPane.YES_OPTION) {return;}
        
        String[] input = {
            InvoiceNumberText.getText(),
            DeliveryNotesNumberText.getText(),
            CustomerNameText.getText(),
            CustomerEmailText.getText(),
            OrderDateText.getText(),
            DeliveryDateText.getText(),
            ItemsText.getText()
        };
        
        mainPage.newSuratJalan(input);
    }//GEN-LAST:event_CreateSuratJalanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateSuratJalanButton;
    private javax.swing.JLabel CustomerEmailLabel;
    private javax.swing.JTextField CustomerEmailText;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField CustomerNameText;
    private javax.swing.JLabel DeliveryDateLabel;
    private javax.swing.JTextField DeliveryDateText;
    private javax.swing.JLabel InvoiceNumberLabel;
    private javax.swing.JTextField InvoiceNumberText;
    private javax.swing.JLabel ItemsLabel;
    private javax.swing.JTextField ItemsText;
    private javax.swing.JLabel OrderDateLabel;
    private javax.swing.JTextField OrderDateText;
    // End of variables declaration//GEN-END:variables
}
