/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;

/**
 *
 * @author micha
 */
public class DaftarItem extends javax.swing.JPanel {

    private MainPage mainPage;
    private ArrayList<Item> items;

    /**
     * Creates new form DaftarItem
     */
    public DaftarItem(MainPage mainPage) {
        initComponents();
        addMainPage(mainPage);
        refresh();
    }

    public void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }

    public final void refresh() {
        items = mainPage.getItem();

        Action detail = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                Item curItem = items.get(modelRow);
                mainPage.onShowItemDescription(curItem);
            }
        };

        ButtonColumn buttonColumn = new ButtonColumn(DaftarItemTable, detail, 7);

        fillTable(items);
        this.SearchField.setText("");
    }

    public final void fillTable(ArrayList<Item> itemList) {
        DefaultTableModel model = (DefaultTableModel) this.DaftarItemTable.getModel();
        model.setRowCount(0);
        Item curItem;
        String status = null;

        for (int i = 0; i < itemList.size(); i++) {
            curItem = itemList.get(i);

            model.addRow(new Object[] { curItem.getBarcode(), curItem.getTitle(), curItem.getDescription(),
                    curItem.getManufacturer(), curItem.getURL(), curItem.getNumberOfStocks(), "Action", "View"});
        }
    }

    public void searchItem(String keyword) {
        items = mainPage.searchItem(keyword);
        fillTable(items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DaftarItemTable = new javax.swing.JTable();
        AddItemButton = new javax.swing.JButton();

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        DaftarItemTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] { { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null } },
                new String[] { "ID", "Barcode", "Title", "Description", "Manufacturer", "URL", "Number of Stocks",
                        "Action" }));
        DaftarItemTable.setRowHeight(35);
        jScrollPane2.setViewportView(DaftarItemTable);

        AddItemButton.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(25, 25, 25)
                                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18).addComponent(SearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddItemButton).addGap(24, 24, 24))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddItemButton))
                        .addGap(18, 18, Short.MAX_VALUE).addComponent(jScrollPane2,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String keyword = SearchField.getText();
        searchItem(keyword);
    }// GEN-LAST:event_SearchButtonActionPerformed

    private void AddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        mainPage.displayAddItems();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JTable DaftarItemTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
