/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;

/**
 *
 * @author micha
 */
public class DeliveryNotesDescription extends javax.swing.JPanel {

    private MainPage mainPage;
    private DeliveryNote deliveryNote;
    /**
     * Creates new form DeliveryNotesDescription
     */
    public DeliveryNotesDescription(MainPage mainPage, DeliveryNote deliveryNote) {
        initComponents();
        addMainPage(mainPage);
        addDeliveryNote(deliveryNote);
        fillFormInput();
    }
    
    public final void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }
    
    public final void addDeliveryNote(DeliveryNote deliveryNote)
    {
        this.deliveryNote = deliveryNote;
    }
    
    public final void fillFormInput()
    {
        this.InvoiceNumberText.setText(deliveryNote.getInvoiceNumber());
        this.DeliveryNotesNumberText.setText(deliveryNote.getDeliveryNotesNumber());
        this.CustomerNameText.setText(deliveryNote.getCustomerName());
        this.OrderDateText.setText(deliveryNote.getOrderDate());
        this.DeliveryDateText.setText(deliveryNote.getDeliveryDate());
        
        switch(deliveryNote.getStatus())
        {
            case 1:
                this.StatusText.setText("New");
                break;
            case 2:
                this.StatusText.setText("Preparing");
                break;
            case 3:
                this.StatusText.setText("Completed");
                break;
            case 4:
                this.StatusText.setText("Pending");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        DNDescTable = new javax.swing.JTable();
        InvoiceNumberLabel = new javax.swing.JLabel();
        InvoiceNumberText = new javax.swing.JTextField();
        DeliveryNotesNumberLabel = new javax.swing.JLabel();
        DeliveryNotesNumberText = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerNameText = new javax.swing.JTextField();
        OrderDateLabel = new javax.swing.JLabel();
        OrderDateText = new javax.swing.JTextField();
        DeliveryDateLabel = new javax.swing.JLabel();
        DeliveryDateText = new javax.swing.JTextField();
        StatusLabel = new javax.swing.JLabel();
        StatusText = new javax.swing.JTextField();
        PendingButton = new javax.swing.JButton();
        SignButton = new javax.swing.JButton();
        PrintButton = new javax.swing.JButton();
        PreparingButton = new javax.swing.JButton();

        DNDescTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Barcode", "Title", "Description", "Manufacturer", "URL", "Number of Stocks", "Action"
            }
        ));
        jScrollPane2.setViewportView(DNDescTable);

        InvoiceNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InvoiceNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InvoiceNumberLabel.setText("Invoice Number");

        InvoiceNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceNumberTextActionPerformed(evt);
            }
        });

        DeliveryNotesNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryNotesNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeliveryNotesNumberLabel.setText("DN Number");

        DeliveryNotesNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryNotesNumberTextActionPerformed(evt);
            }
        });

        CustomerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CustomerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerNameLabel.setText("Cust Name");

        CustomerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTextActionPerformed(evt);
            }
        });

        OrderDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrderDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OrderDateLabel.setText("Order Date");

        OrderDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDateTextActionPerformed(evt);
            }
        });

        DeliveryDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeliveryDateLabel.setText("Delivery Date");

        DeliveryDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryDateTextActionPerformed(evt);
            }
        });

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StatusLabel.setText("Status");

        StatusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTextActionPerformed(evt);
            }
        });

        PendingButton.setText("Pending");

        SignButton.setText("Sign");
        SignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignButtonActionPerformed(evt);
            }
        });

        PrintButton.setText("Print");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        PreparingButton.setText("Preparing");
        PreparingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreparingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InvoiceNumberLabel)
                    .addComponent(DeliveryNotesNumberLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderDateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeliveryDateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoiceNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryNotesNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreparingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoiceNumberText)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InvoiceNumberLabel)
                        .addComponent(PendingButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeliveryNotesNumberLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeliveryNotesNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SignButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderDateLabel)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreparingButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeliveryDateLabel)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLabel)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveryNotesNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryNotesNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryNotesNumberTextActionPerformed

    private void StatusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTextActionPerformed

    private void DeliveryDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryDateTextActionPerformed

    private void OrderDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderDateTextActionPerformed

    private void CustomerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameTextActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void SignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignButtonActionPerformed

    private void InvoiceNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoiceNumberTextActionPerformed

    private void PreparingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreparingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreparingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField CustomerNameText;
    private javax.swing.JTable DNDescTable;
    private javax.swing.JLabel DeliveryDateLabel;
    private javax.swing.JTextField DeliveryDateText;
    private javax.swing.JLabel DeliveryNotesNumberLabel;
    private javax.swing.JTextField DeliveryNotesNumberText;
    private javax.swing.JLabel InvoiceNumberLabel;
    private javax.swing.JTextField InvoiceNumberText;
    private javax.swing.JLabel OrderDateLabel;
    private javax.swing.JTextField OrderDateText;
    private javax.swing.JButton PendingButton;
    private javax.swing.JButton PreparingButton;
    private javax.swing.JButton PrintButton;
    private javax.swing.JButton SignButton;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField StatusText;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
