/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;

/**
 *
 * @author micha
 */
public class EmailDeliveryNotesForm extends javax.swing.JPanel {

    private MainPage mainPage;
    private DeliveryNote deliveryNote;
    /**
     * Creates new form EmailDeliveryNotesForm
     */
    public EmailDeliveryNotesForm(MainPage mainPage, DeliveryNote deliveryNote) {
        initComponents();
        this.deliveryNote = deliveryNote;
        addMainPage(mainPage);
        fillDefaults();
    }

    private void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }
    
    private void fillDefaults() {
        EmailToText.setText(deliveryNote.getCustomerEmail());
        SubjectText.setText("Delivery Note : #" + deliveryNote.getDeliveryNotesNumber());
        BodyTextArea.setText(deliveryNote.details());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailToLabel = new javax.swing.JLabel();
        EmailToText = new javax.swing.JTextField();
        SubjectLabel = new javax.swing.JLabel();
        SubjectText = new javax.swing.JTextField();
        BodyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BodyTextArea = new javax.swing.JTextArea();
        SendButton = new javax.swing.JButton();

        EmailToLabel.setText("Email To");

        SubjectLabel.setText("Subject");

        BodyLabel.setText("Body");

        BodyTextArea.setColumns(20);
        BodyTextArea.setRows(5);
        jScrollPane1.setViewportView(BodyTextArea);

        SendButton.setText("Send Email");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubjectLabel)
                    .addComponent(BodyLabel)
                    .addComponent(EmailToLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailToText, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(SubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailToLabel)
                    .addComponent(EmailToText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectLabel)
                    .addComponent(SubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BodyLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        // TODO add your handling code here:
        mainPage.emailSend(EmailToText.getText(), SubjectText.getText(), BodyTextArea.getText());
    }//GEN-LAST:event_SendButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BodyLabel;
    private javax.swing.JTextArea BodyTextArea;
    private javax.swing.JLabel EmailToLabel;
    private javax.swing.JTextField EmailToText;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JTextField SubjectText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
