/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;

import javax.swing.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;

/**
 *
 * @author micha
 */
public class Invoices extends javax.swing.JPanel {

    private MainPage mainPage;
    private ArrayList<Invoice> invoices;

    /**
     * Creates new form Invoices
     */
    public Invoices(MainPage mainPage) {
        initComponents();
        addMainPage(mainPage);
        refresh();
    }

    public void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }

    public final void refresh() {
        invoices = mainPage.getInvoice();

        Action detail = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                Invoice curInvoice = invoices.get(modelRow);
                mainPage.onShowInvoiceDescription(curInvoice);
            }
        };

        ButtonColumn buttonColumn = new ButtonColumn(DaftarInvoiceTable, detail, 6);

        fillTable(invoices);
        this.SearchField.setText("");
    }

    public final void fillTable(ArrayList<Invoice> invoiceList) {
        DefaultTableModel model = (DefaultTableModel) this.DaftarInvoiceTable.getModel();
        model.setRowCount(0);
        Invoice curInvoice;
        String status = null;

        for (int i = 0; i < invoiceList.size(); i++) {
            curInvoice = invoiceList.get(i);

            switch (curInvoice.getStatus()) {
                case 1:
                    status = "New";
                    break;
                case 2:
                    status = "Completed";
                    break;
                case 3:
                    status = "Pending";
                    break;
            }

            model.addRow(new Object[] { curInvoice.getId(), curInvoice.getPoNumber(), curInvoice.getSupplierName(),
                    curInvoice.getOrderDate(), curInvoice.getDeliveryDate(), status, "View" });
        }
    }

    public void searchInvoice(String keyword) {
        invoices = mainPage.searchInvoice(keyword);
        // invoices = mainPage.getInvoice();

        fillTable(invoices);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DaftarInvoiceTable = new javax.swing.JTable();
        AddInvoiceButton = new javax.swing.JButton();

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        DaftarInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] { { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null } },
                new String[] { "Inv Number", "PO Number", "Supp Name", "Order Date", "Delivery Date", "Status",
                        "Action" }));
        DaftarInvoiceTable.setRowHeight(35);
        jScrollPane1.setViewportView(DaftarInvoiceTable);

        AddInvoiceButton.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(25, 25, 25)
                                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18).addComponent(SearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddInvoiceButton).addGap(24, 24, 24))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddInvoiceButton))
                        .addGap(18, 18, Short.MAX_VALUE).addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String keyword = SearchField.getText();
        searchInvoice(keyword);
    }// GEN-LAST:event_SearchButtonActionPerformed

    private void AddInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        mainPage.displayAddInvoices();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInvoiceButton;
    private javax.swing.JTable DaftarInvoiceTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
