/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;

/**
 *
 * @author micha
 */
public class InvoiceDescription extends javax.swing.JPanel {

    private MainPage mainPage;
    private Invoice invoice;
    /**
     * Creates new form InvoiceDescription
     */
    public InvoiceDescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        InvoiceNumberLabel = new javax.swing.JLabel();
        PONumberLabel = new javax.swing.JLabel();
        SupplierNameLabel = new javax.swing.JLabel();
        OrderDateLabel = new javax.swing.JLabel();
        DeliveryDateLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        InvoiceNumberText = new javax.swing.JTextField();
        PONumberText = new javax.swing.JTextField();
        StatusText = new javax.swing.JTextField();
        DeliveryDateText = new javax.swing.JTextField();
        OrderDateText = new javax.swing.JTextField();
        SupplierNameText = new javax.swing.JTextField();
        PendingButton = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Barcode", "Title", "Description", "Manufacturer", "URL", "Number of Stocks", "Action"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        InvoiceNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InvoiceNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InvoiceNumberLabel.setText("Invoice Number");

        PONumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PONumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PONumberLabel.setText("PO Number");

        SupplierNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SupplierNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SupplierNameLabel.setText("Supplier Name");

        OrderDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrderDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OrderDateLabel.setText("Order Date");

        DeliveryDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeliveryDateLabel.setText("Delivery Date");

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StatusLabel.setText("Status");

        InvoiceNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceNumberTextActionPerformed(evt);
            }
        });

        PONumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PONumberTextActionPerformed(evt);
            }
        });

        StatusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTextActionPerformed(evt);
            }
        });

        DeliveryDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryDateTextActionPerformed(evt);
            }
        });

        OrderDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDateTextActionPerformed(evt);
            }
        });

        SupplierNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierNameTextActionPerformed(evt);
            }
        });

        PendingButton.setText("Pending");
        PendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButtonActionPerformed(evt);
            }
        });

        AcceptButton.setText("Accept");
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InvoiceNumberLabel)
                    .addComponent(PONumberLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplierNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderDateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeliveryDateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoiceNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PONumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoiceNumberText)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InvoiceNumberLabel)
                        .addComponent(PendingButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PONumberLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PONumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AcceptButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierNameLabel)
                    .addComponent(SupplierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderDateLabel)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeliveryDateLabel)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLabel)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InvoiceNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoiceNumberTextActionPerformed

    private void PONumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PONumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PONumberTextActionPerformed

    private void StatusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTextActionPerformed

    private void DeliveryDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryDateTextActionPerformed

    private void OrderDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderDateTextActionPerformed

    private void SupplierNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierNameTextActionPerformed

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void PendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JLabel DeliveryDateLabel;
    private javax.swing.JTextField DeliveryDateText;
    private javax.swing.JLabel InvoiceNumberLabel;
    private javax.swing.JTextField InvoiceNumberText;
    private javax.swing.JLabel OrderDateLabel;
    private javax.swing.JTextField OrderDateText;
    private javax.swing.JLabel PONumberLabel;
    private javax.swing.JTextField PONumberText;
    private javax.swing.JButton PendingButton;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField StatusText;
    private javax.swing.JLabel SupplierNameLabel;
    private javax.swing.JTextField SupplierNameText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
