/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;

/**
 *
 * @author Kevin
 */
public class ItemDescription extends javax.swing.JPanel {

    /**
     * Creates new form ItemDescription
     */
    public ItemDescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoiceNumberLabel = new javax.swing.JLabel();
        StatusText = new javax.swing.JTextField();
        InvoiceNumberText = new javax.swing.JTextField();
        PendingButton = new javax.swing.JButton();
        DeliveryNotesNumberLabel = new javax.swing.JLabel();
        DeliveryNotesNumberText = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerNameText = new javax.swing.JTextField();
        OrderDateLabel = new javax.swing.JLabel();
        OrderDateText = new javax.swing.JTextField();
        DeliveryDateLabel = new javax.swing.JLabel();
        DeliveryDateText = new javax.swing.JTextField();
        StatusLabel = new javax.swing.JLabel();
        StatusLabel1 = new javax.swing.JLabel();
        StatusText1 = new javax.swing.JTextField();

        InvoiceNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InvoiceNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InvoiceNumberLabel.setText("ID");

        StatusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTextActionPerformed(evt);
            }
        });

        InvoiceNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceNumberTextActionPerformed(evt);
            }
        });

        PendingButton.setText("Update");
        PendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButtonActionPerformed(evt);
            }
        });

        DeliveryNotesNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryNotesNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeliveryNotesNumberLabel.setText("Barcode");

        DeliveryNotesNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryNotesNumberTextActionPerformed(evt);
            }
        });

        CustomerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CustomerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerNameLabel.setText("Title");

        CustomerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTextActionPerformed(evt);
            }
        });

        OrderDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrderDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OrderDateLabel.setText("Description");

        OrderDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDateTextActionPerformed(evt);
            }
        });

        DeliveryDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveryDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeliveryDateLabel.setText("Manufacturer");

        DeliveryDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryDateTextActionPerformed(evt);
            }
        });

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StatusLabel.setText("URL");

        StatusLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StatusLabel1.setText("Number Of Stocks");

        StatusText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusText1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeliveryNotesNumberLabel)
                    .addComponent(CustomerNameLabel)
                    .addComponent(OrderDateLabel)
                    .addComponent(DeliveryDateLabel)
                    .addComponent(StatusLabel)
                    .addComponent(StatusLabel1)
                    .addComponent(InvoiceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoiceNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryNotesNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusText1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(650, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(861, Short.MAX_VALUE)
                    .addComponent(PendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvoiceNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvoiceNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeliveryNotesNumberLabel)
                    .addComponent(DeliveryNotesNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderDateLabel)
                    .addComponent(OrderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeliveryDateLabel)
                    .addComponent(DeliveryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLabel)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusLabel1))
                .addGap(51, 51, 51))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(PendingButton)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StatusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTextActionPerformed

    private void InvoiceNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoiceNumberTextActionPerformed

    private void DeliveryNotesNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryNotesNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryNotesNumberTextActionPerformed

    private void CustomerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameTextActionPerformed

    private void OrderDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderDateTextActionPerformed

    private void DeliveryDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryDateTextActionPerformed

    private void StatusText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusText1ActionPerformed

    private void PendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField CustomerNameText;
    private javax.swing.JLabel DeliveryDateLabel;
    private javax.swing.JTextField DeliveryDateText;
    private javax.swing.JLabel DeliveryNotesNumberLabel;
    private javax.swing.JTextField DeliveryNotesNumberText;
    private javax.swing.JLabel InvoiceNumberLabel;
    private javax.swing.JTextField InvoiceNumberText;
    private javax.swing.JLabel OrderDateLabel;
    private javax.swing.JTextField OrderDateText;
    private javax.swing.JButton PendingButton;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel StatusLabel1;
    private javax.swing.JTextField StatusText;
    private javax.swing.JTextField StatusText1;
    // End of variables declaration//GEN-END:variables
}
