/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gacha.silo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Kevin
 */
public class ItemDescription extends javax.swing.JPanel {

    private MainPage mainPage;
    private Item item;
    /**
     * Creates new form ItemDescription
     */
    public ItemDescription(MainPage mainPage, Item item) {
        initComponents();
        addMainPage(mainPage);
        addItem(item);
        fillFormInput();
    }
    
    public final void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }
    
    public final void addItem(Item item)
    {
        this.item = item;
    }
    
    public final void fillFormInput()
    {
        this.IdText.setText(item.getId());
        this.BarcodeText.setText(item.getBarcode());
        this.TitleText.setText(item.getTitle());
        this.DescriptionText.setText(item.getDescription());
        this.ManufacturerText.setText(item.getManufacturer());
        this.UrlText.setText(item.getURL());
        this.NumberOfStocksText.setText(item.getNumberOfStocks());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdLabel = new javax.swing.JLabel();
        UrlText = new javax.swing.JTextField();
        IdText = new javax.swing.JTextField();
        PendingButton = new javax.swing.JButton();
        BarcodeLabel = new javax.swing.JLabel();
        BarcodeText = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        TitleText = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        DescriptionText = new javax.swing.JTextField();
        ManufacturerLabel = new javax.swing.JLabel();
        ManufacturerText = new javax.swing.JTextField();
        UrlLabel = new javax.swing.JLabel();
        NumberOfStocksLabel = new javax.swing.JLabel();
        NumberOfStocksText = new javax.swing.JTextField();

        IdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IdLabel.setText("ID");

        UrlText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrlTextActionPerformed(evt);
            }
        });

        IdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextActionPerformed(evt);
            }
        });

        PendingButton.setText("Update");
        PendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButtonActionPerformed(evt);
            }
        });

        BarcodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BarcodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BarcodeLabel.setText("Barcode");

        BarcodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarcodeTextActionPerformed(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TitleLabel.setText("Title");

        TitleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextActionPerformed(evt);
            }
        });

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DescriptionLabel.setText("Description");

        DescriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionTextActionPerformed(evt);
            }
        });

        ManufacturerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManufacturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManufacturerLabel.setText("Manufacturer");

        ManufacturerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufacturerTextActionPerformed(evt);
            }
        });

        UrlLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UrlLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UrlLabel.setText("URL");

        NumberOfStocksLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumberOfStocksLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NumberOfStocksLabel.setText("Number Of Stocks");

        NumberOfStocksText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfStocksTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarcodeLabel)
                    .addComponent(TitleLabel)
                    .addComponent(DescriptionLabel)
                    .addComponent(ManufacturerLabel)
                    .addComponent(UrlLabel)
                    .addComponent(NumberOfStocksLabel)
                    .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BarcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UrlText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManufacturerText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberOfStocksText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(650, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(861, Short.MAX_VALUE)
                    .addComponent(PendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel)
                    .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarcodeLabel)
                    .addComponent(BarcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLabel)
                    .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionLabel)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManufacturerLabel)
                    .addComponent(ManufacturerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UrlLabel)
                    .addComponent(UrlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfStocksText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberOfStocksLabel))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(PendingButton)
                    .addContainerGap(295, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UrlTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrlTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrlTextActionPerformed

    private void IdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextActionPerformed

    private void BarcodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarcodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarcodeTextActionPerformed

    private void TitleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleTextActionPerformed

    private void DescriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionTextActionPerformed

    private void ManufacturerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufacturerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufacturerTextActionPerformed

    private void NumberOfStocksTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfStocksTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfStocksTextActionPerformed

    private void PendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarcodeLabel;
    private javax.swing.JTextField BarcodeText;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField IdText;
    private javax.swing.JLabel ManufacturerLabel;
    private javax.swing.JTextField ManufacturerText;
    private javax.swing.JLabel NumberOfStocksLabel;
    private javax.swing.JTextField NumberOfStocksText;
    private javax.swing.JButton PendingButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TitleText;
    private javax.swing.JLabel UrlLabel;
    private javax.swing.JTextField UrlText;
    // End of variables declaration//GEN-END:variables
}
